import {
  HIA_SOURCE_MODEL,
  HIA_SOURCE_MODEL_VERSION,
  HIA_TEXT_I18N_MODEL,
  HIA_TEXT_I18N_MODEL_VERSION,
  createHiaDiagnostic,
  createHiaDocument
} from "@hia-doc/core";
import type {
  HiaDiagnostic,
  HiaDiagnosticData,
  HiaDiagnosticSeverity,
  HiaDocument,
  HiaFallbackLocale,
  HiaI18nField,
  HiaI18nModel,
  HiaI18nResource,
  HiaLangBlock,
  HiaLangInlineSegment,
  HiaLocalizedText,
  HiaNode,
  HiaSourceConfidence,
  HiaSourceDefinedIn,
  HiaSourceFragment,
  HiaSourceLink,
  HiaSourceMetadata,
  HiaSourceMode,
  HiaSourcePosition,
  HiaSourcePreview,
  HiaSourcePrimaryBlock,
  HiaSourceRange,
  HiaSourceRangeSource,
  HiaSourceReference,
  HiaSymbol,
  HiaTextResolution
} from "@hia-doc/core";

/**
 * Stable adapter id used in HIA document metadata generated from JSDoc integration artifacts.
 *
 * 中文：声明 JSDoc integration 到 HIA document 适配层的稳定标识，用于 metadata、诊断和后续 drift 检查。
 * English: Declares the stable adapter id for JSDoc integration to HIA document conversion metadata, diagnostics and drift checks.
 */
export const JSDOC_ADAPTER_NAME = "parser-jsdoc";

/**
 * Version of the adapter bridge that maps JSDoc integration data into HIA core document shapes.
 *
 * 中文：标识当前 JSDoc adapter 与 HIA core document 之间的桥接版本。
 * English: Identifies the bridge version between the JSDoc adapter and HIA core document model.
 */
export const JSDOC_ADAPTER_CORE_BRIDGE_VERSION = "0.1.0";

/**
 * Version of the adapter-owned metadata object stored on generated HIA documents.
 *
 * 中文：标识生成文档中由 adapter 负责维护的 metadata schema 版本。
 * English: Identifies the adapter-owned metadata schema version stored on generated documents.
 */
export const JSDOC_ADAPTER_METADATA_SCHEMA_VERSION = "0.1.0";

/**
 * Contract name expected from `jsdoc-plugin-hia-sys` integration output.
 *
 * 中文：声明 `jsdoc-plugin-hia-sys` integration artifact 的输入契约名。
 * English: Declares the input contract name for `jsdoc-plugin-hia-sys` integration artifacts.
 */
export const JSDOC_HIA_INTEGRATION_CONTRACT = "hia-jsdoc-integration";

/**
 * Contract version expected from `jsdoc-plugin-hia-sys` integration output.
 *
 * 中文：声明当前 adapter 支持的 JSDoc HIA integration artifact 契约版本。
 * English: Declares the JSDoc HIA integration artifact contract version supported by this adapter.
 */
export const JSDOC_HIA_INTEGRATION_CONTRACT_VERSION = "0.1.0";

/**
 * Metadata copied from a JSDoc HIA integration artifact into generated HIA document metadata.
 *
 * 中文：描述从 JSDoc HIA integration artifact 复制到 HIA document metadata 的兼容性和溯源信息。
 * English: Describes compatibility and provenance metadata copied from a JSDoc HIA integration artifact into HIA document metadata.
 */
export interface JSDocAdapterIntegrationMetadata extends Record<string, unknown> {
  /** 中文：integration artifact 契约名。English: Integration artifact contract name. */
  contract: string;
  /** 中文：integration artifact 契约版本。English: Integration artifact contract version. */
  contractVersion: string;
  /** 中文：生成 artifact 的 JPHS 插件版本。English: JPHS plugin version that produced the artifact. */
  pluginVersion: string;
  /** 中文：JSDoc/HIA 输出模式。English: JSDoc/HIA output mode. */
  mode: string;
  /** 中文：JSDoc integration IR 版本。English: JSDoc integration IR version. */
  irVersion: string;
  /** 中文：已清理的 parser 边界 metadata。English: Sanitized parser boundary metadata. */
  parserBoundary: unknown;
  /** 中文：已过滤的 doclet 与 HIA node 映射。English: Filtered doclet-to-HIA-node mapping. */
  docletNodeMap: unknown;
  /** 中文：已清理的源码片段 metadata。English: Sanitized source fragment metadata. */
  sourceFragments: unknown;
  /** 中文：已清理的本地化资源 metadata。English: Sanitized localization resource metadata. */
  localizationResources: unknown;
  /** 中文：上游诊断数量摘要。English: Upstream diagnostic count summary. */
  diagnosticCounts: unknown;
}

/**
 * Adapter metadata stored on a HIA document converted from JSDoc integration output.
 *
 * 中文：描述 JSDoc adapter 生成的 HIA document metadata 根对象。
 * English: Describes the root metadata object generated by the JSDoc adapter on a HIA document.
 */
export interface JSDocAdapterDocumentMetadata extends Record<string, unknown> {
  /** 中文：固定 adapter 标识。English: Stable adapter identifier. */
  adapter: typeof JSDOC_ADAPTER_NAME;
  /** 中文：adapter/core bridge 版本。English: Adapter/core bridge version. */
  adapterBridgeVersion: typeof JSDOC_ADAPTER_CORE_BRIDGE_VERSION;
  /** 中文：adapter metadata schema 版本。English: Adapter metadata schema version. */
  metadataSchemaVersion: typeof JSDOC_ADAPTER_METADATA_SCHEMA_VERSION;
  /** 中文：源 artifact 类型。English: Source artifact family. */
  source: "jsdoc";
  /** 中文：从 integration artifact 继承的溯源 metadata。English: Provenance metadata inherited from the integration artifact. */
  integration: JSDocAdapterIntegrationMetadata;
}

/**
 * Loose input shape accepted from JPHS/JSDoc integration JSON.
 *
 * 中文：定义 adapter 可接受的宽松 JSDoc integration 输入形态；字段在转换时会被校验和清理。
 * English: Defines the loose JSDoc integration input shape accepted by the adapter; fields are validated and sanitized during conversion.
 */
export interface JSDocIntegrationInput {
  /** 中文：可选契约名；不匹配时产生 warning。English: Optional contract name; mismatches produce warnings. */
  contract?: string;
  /** 中文：可选契约版本；不匹配时产生 warning。English: Optional contract version; mismatches produce warnings. */
  contractVersion?: string;
  /** 中文：生成该 artifact 的插件版本。English: Plugin version that produced the artifact. */
  pluginVersion?: string;
  /** 中文：JSDoc/HIA 输出模式。English: JSDoc/HIA output mode. */
  mode?: string;
  /** 中文：parser 边界 metadata。English: Parser boundary metadata. */
  parserBoundary?: Record<string, unknown>;
  /** 中文：JSDoc integration 中间表示。English: JSDoc integration intermediate representation. */
  ir?: {
    /** 中文：IR 版本。English: IR version. */
    version?: string;
    /** 中文：IR 来源名称。English: IR source name. */
    source?: string;
    /** 中文：待转换的 JSDoc/HIA 节点。English: JSDoc/HIA nodes to convert. */
    nodes?: unknown[];
  };
  /** 中文：上游源码片段集合。English: Upstream source fragment collection. */
  sourceFragments?: unknown[];
  /** 中文：上游本地化资源集合。English: Upstream localization resource collection. */
  localizationResources?: unknown[];
  /** 中文：上游诊断集合。English: Upstream diagnostic collection. */
  diagnostics?: unknown[];
  /** 中文：上游诊断数量摘要。English: Upstream diagnostic count summary. */
  diagnosticCounts?: Record<string, unknown>;
  /** 中文：doclet 与节点的映射集合。English: Doclet-to-node mapping collection. */
  docletNodeMap?: unknown[];
}

/**
 * Options for converting JSDoc integration artifacts into HIA documents.
 *
 * 中文：控制 JSDoc integration artifact 转换为 HIA document 的文档标识、本地化和空符号策略。
 * English: Controls document identity, localization and empty-symbol behavior when converting JSDoc integration artifacts into HIA documents.
 */
export interface ConvertJSDocIntegrationOptions {
  /** 中文：生成 HIA document 的 id。English: Generated HIA document id. */
  documentId?: string;
  /** 中文：生成 HIA document 的标题。English: Generated HIA document title. */
  title?: string;
  /** 中文：默认 locale。English: Default locale. */
  defaultLocale?: string;
  /** 中文：fallback locale 或 fallback 链。English: Fallback locale or fallback chain. */
  fallbackLocale?: HiaFallbackLocale;
  /** 中文：允许写入文档的 locale 列表。English: Locales allowed in the generated document. */
  locales?: string[];
  /** 中文：是否保留缺少用户可见内容的符号。English: Whether symbols without user-facing content are retained. */
  includeEmptySymbols?: boolean;
}

/**
 * Detailed conversion result containing both the document and adapter diagnostics.
 *
 * 中文：保留转换后的 HIA document 与转换过程中产生的 adapter diagnostics。
 * English: Carries the converted HIA document and adapter diagnostics produced during conversion.
 */
export interface ConvertJSDocIntegrationResult {
  /** 中文：转换后的 HIA document。English: Converted HIA document. */
  document: HiaDocument;
  /** 中文：转换和上游 artifact 映射产生的诊断。English: Diagnostics produced by conversion and upstream artifact mapping. */
  diagnostics: HiaDiagnostic[];
}

/**
 * Converts a JSDoc HIA integration artifact into a HIA core document.
 *
 * 中文：将 JPHS/JSDoc integration JSON 转换为 HIA core document；若输入无效则返回带 error diagnostic 的空文档。
 * English: Converts JPHS/JSDoc integration JSON into a HIA core document; invalid input returns an empty document with an error diagnostic.
 *
 * @param input - Unknown JSDoc integration JSON value.
 * @param options - Optional document identity, locale and filtering options.
 * @returns A HIA document generated from the integration artifact.
 */
export function convertJSDocIntegrationToHiaDocument(
  input: unknown,
  options: ConvertJSDocIntegrationOptions = {}
): HiaDocument {
  return convertJSDocIntegrationToHiaDocumentDetailed(input, options).document;
}

/**
 * Converts a JSDoc HIA integration artifact into a HIA core document with diagnostics.
 *
 * 中文：执行完整转换并返回文档与诊断；适合 gate、测试和上层 producer 在不丢失 warning 的情况下消费。
 * English: Runs the full conversion and returns both document and diagnostics, allowing gates, tests and producers to consume warnings without losing them.
 *
 * @param input - Unknown JSDoc integration JSON value.
 * @param options - Optional document identity, locale and filtering options.
 * @returns A detailed conversion result containing the generated document and diagnostics.
 */
export function convertJSDocIntegrationToHiaDocumentDetailed(
  input: unknown,
  options: ConvertJSDocIntegrationOptions = {}
): ConvertJSDocIntegrationResult {
  const diagnostics: HiaDiagnostic[] = [];

  if (!isRecord(input)) {
    diagnostics.push(createDiagnostic(
      "HIA_JSDOC_INTEGRATION_INVALID",
      "JSDoc integration input must be an object.",
      "error"
    ));

    const emptyDocument = createHiaDocument({
      id: options.documentId ?? "jsdoc.integration",
      title: options.title ?? "JSDoc Integration",
      defaultLocale: options.defaultLocale ?? "en",
      locales: options.locales ?? [options.defaultLocale ?? "en"],
      diagnostics
    });

    return {
      document: emptyDocument,
      diagnostics
    };
  }

  const integration = input as JSDocIntegrationInput;

  if (integration.contract && integration.contract !== JSDOC_HIA_INTEGRATION_CONTRACT) {
    diagnostics.push(createDiagnostic(
      "HIA_JSDOC_CONTRACT_UNSUPPORTED",
      `Unsupported JSDoc integration contract: ${integration.contract}.`,
      "warning",
      "contract",
      {
        actualContract: integration.contract,
        expectedContract: JSDOC_HIA_INTEGRATION_CONTRACT
      }
    ));
  }

  if (integration.contractVersion && integration.contractVersion !== JSDOC_HIA_INTEGRATION_CONTRACT_VERSION) {
    diagnostics.push(createDiagnostic(
      "HIA_JSDOC_CONTRACT_VERSION_UNSUPPORTED",
      `Unsupported JSDoc integration contractVersion: ${integration.contractVersion}.`,
      "warning",
      "contractVersion",
      {
        actualVersion: integration.contractVersion,
        expectedVersion: JSDOC_HIA_INTEGRATION_CONTRACT_VERSION
      }
    ));
  }

  const sourceNodes = Array.isArray(integration.ir?.nodes) ? integration.ir.nodes : [];
  const defaultLocale = options.defaultLocale ?? findFirstString(sourceNodes, "i18n.defaultLocale") ?? "en";
  const fallbackLocale = options.fallbackLocale ?? findFirstFallbackLocale(sourceNodes);
  const locales = collectLocales(sourceNodes, options.locales, defaultLocale);
  const mappedSymbols = sourceNodes
    .map((node, index) => mapIntegrationNodeToSymbol(node, index, defaultLocale, fallbackLocale, locales, diagnostics))
    .filter((symbol): symbol is HiaSymbol => Boolean(symbol))
    .filter((symbol) => options.includeEmptySymbols || symbol.name.length > 0);
  const symbols = dedupeSymbols(mappedSymbols
    .filter((symbol) => options.includeEmptySymbols || hasUserFacingSymbolContent(symbol)));
  const documentNodes: HiaNode[] = symbols.length > 0
    ? [
        {
          id: "node.jsdoc",
          kind: "group",
          title: "JSDoc",
          symbolIds: symbols.map((symbol) => symbol.id),
          children: []
        }
      ]
    : [];
  const documentDiagnostics = [
    ...mapDiagnostics(integration.diagnostics, "diagnostics"),
    ...diagnostics
  ];
  const symbolIds = new Set(symbols.map((symbol) => symbol.id));
  const adapterMetadata: JSDocAdapterDocumentMetadata = {
    adapter: JSDOC_ADAPTER_NAME,
    adapterBridgeVersion: JSDOC_ADAPTER_CORE_BRIDGE_VERSION,
    metadataSchemaVersion: JSDOC_ADAPTER_METADATA_SCHEMA_VERSION,
    source: "jsdoc",
    integration: {
      contract: integration.contract ?? "",
      contractVersion: integration.contractVersion ?? "",
      pluginVersion: integration.pluginVersion ?? "",
      mode: integration.mode ?? "",
      irVersion: integration.ir?.version ?? "",
      parserBoundary: sanitizeMetadata(integration.parserBoundary ?? {}),
      docletNodeMap: sanitizeMetadata(filterDocletNodeMap(integration.docletNodeMap, symbolIds)),
      sourceFragments: sanitizeMetadata(integration.sourceFragments ?? []),
      localizationResources: sanitizeMetadata(integration.localizationResources ?? []),
      diagnosticCounts: sanitizeMetadata(integration.diagnosticCounts ?? {})
    }
  };
  const documentInput = {
    id: options.documentId ?? "jsdoc.integration",
    title: options.title ?? "JSDoc Integration",
    defaultLocale,
    locales,
    nodes: documentNodes,
    symbols,
    diagnostics: documentDiagnostics,
    metadata: adapterMetadata
  };

  if (fallbackLocale) {
    Object.assign(documentInput, { fallbackLocale });
  }

  const document = createHiaDocument(documentInput);

  return {
    document,
    diagnostics: documentDiagnostics
  };
}

/**
 * Alias for `convertJSDocIntegrationToHiaDocument`.
 *
 * 中文：提供较短的兼容入口，便于上层代码表达“从 JSDoc integration 生成 HIA document”。
 * English: Provides a shorter compatibility entry point for expressing "create a HIA document from JSDoc integration".
 */
export const fromJSDocIntegration = convertJSDocIntegrationToHiaDocument;

function mapIntegrationNodeToSymbol(
  node: unknown,
  index: number,
  defaultLocale: string,
  fallbackLocale: HiaFallbackLocale | undefined,
  locales: string[],
  diagnostics: HiaDiagnostic[]
): HiaSymbol | null {
  if (!isRecord(node)) {
    diagnostics.push(createDiagnostic(
      "HIA_JSDOC_NODE_INVALID",
      "JSDoc integration node must be an object.",
      "warning",
      `ir.nodes.${index}`
    ));
    return null;
  }

  const kind = stringValue(node.kind) || "unknown";
  const id = stringValue(node.id) || `jsdoc:${kind}:${index}`;
  const longname = stringValue(node.longname);
  const name = stringValue(node.name) || longname || id;
  const i18n = mapI18nModel(node.i18n, defaultLocale, fallbackLocale, locales);
  const summary = chooseSummary(node, i18n, defaultLocale);
  const symbol: HiaSymbol = {
    id,
    name,
    kind,
    metadata: {
      adapter: JSDOC_ADAPTER_NAME,
      metadataSchemaVersion: JSDOC_ADAPTER_METADATA_SCHEMA_VERSION,
      jsdoc: sanitizeMetadata(node.jsdoc ?? {}),
      hia: sanitizeMetadata(node.hia ?? {})
    }
  };
  const source = mapSourceMetadata(node.source);
  const nodeDiagnostics = mapDiagnostics(node.diagnostics, `symbols.${index}.diagnostics`);

  if (summary) {
    symbol.summary = summary;
  }

  if (longname) {
    symbol.longname = longname;
  }

  const path = findFirstString([node], "i18n.path");
  if (path) {
    symbol.path = path.split(".").filter(Boolean);
  }

  if (i18n) {
    symbol.i18n = i18n;
  }

  if (source) {
    symbol.source = source;
  }

  if (nodeDiagnostics.length > 0) {
    symbol.diagnostics = nodeDiagnostics;
  }

  return symbol;
}

function mapI18nModel(
  value: unknown,
  defaultLocale: string,
  fallbackLocale: HiaFallbackLocale | undefined,
  locales: string[]
): HiaI18nModel | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const fields = mapI18nFields(value.fields, defaultLocale, {
    descriptionKey: stringValue(value.key),
    descriptionPath: stringValue(value.path)
  });
  const model: HiaI18nModel = {
    enabled: value.enabled !== false,
    model: HIA_TEXT_I18N_MODEL,
    modelVersion: HIA_TEXT_I18N_MODEL_VERSION,
    defaultLocale: stringValue(value.defaultLocale) || defaultLocale,
    locales: collectStringArray(value.locales, locales),
    fields
  };
  const resolvedFallbackLocale = value.fallbackLocale ?? fallbackLocale;
  const mode = stringValue(value.mode);
  const resources = mapI18nResources(value.resources);
  const diagnostics = mapDiagnostics(value.diagnostics, "i18n.diagnostics");

  if (resolvedFallbackLocale) {
    const normalizedFallbackLocale = normalizeFallbackLocale(resolvedFallbackLocale);

    if (normalizedFallbackLocale) {
      model.fallbackLocale = normalizedFallbackLocale;
    }
  }

  if (mode) {
    model.mode = mode;
  }

  if (resources.length > 0) {
    model.resources = resources;
  }

  if (diagnostics.length > 0) {
    model.diagnostics = diagnostics;
  }

  return model;
}

function mapI18nFields(
  value: unknown,
  defaultLocale: string,
  options: { descriptionKey?: string; descriptionPath?: string } = {}
): Record<string, HiaI18nField> {
  if (!isRecord(value)) {
    return {};
  }

  const fields: Record<string, HiaI18nField> = {};

  for (const [fieldPath, rawField] of Object.entries(value)) {
    if (!isRecord(rawField)) {
      continue;
    }

    const localizedText = mapLocalizedText(rawField.localizedText);
    const defaultText = stringValue(rawField.defaultText);

    if (Object.keys(localizedText).length === 0 && defaultText) {
      localizedText[defaultLocale] = defaultText;
    }

    const field: HiaI18nField = {
      fieldPath: stringValue(rawField.fieldPath) || fieldPath,
      kind: stringValue(rawField.kind) || fieldPath,
      defaultLocale: stringValue(rawField.defaultLocale) || defaultLocale,
      localizedText
    };
    const key = stringValue(rawField.key) || (fieldPath === "description" ? options.descriptionKey || "" : "");
    const path = stringValue(rawField.path) || (fieldPath === "description" ? options.descriptionPath || "" : "");
    const source = stringValue(rawField.source);
    const blocks = mapLangBlocks(rawField.blocks, field.fieldPath);
    const segments = mapLangInlineSegments(rawField.segments, field.fieldPath);
    const resolutions = mapTextResolutions(rawField.resolutions);
    const missingLocales = collectStringArray(rawField.missingLocales);

    if (key) {
      field.key = key;
    }

    if (path) {
      field.path = path;
    }

    if (defaultText) {
      field.defaultText = defaultText;
    }

    if (source) {
      field.source = source;
    }

    if (blocks.length > 0) {
      field.blocks = blocks;
    }

    if (segments.length > 0) {
      field.segments = segments;
    }

    if (Object.keys(resolutions).length > 0) {
      field.resolutions = resolutions;
    }

    if (missingLocales.length > 0) {
      field.missingLocales = missingLocales;
    }

    fields[fieldPath] = field;
  }

  return fields;
}

function mapSourceMetadata(value: unknown): HiaSourceMetadata | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const source: HiaSourceMetadata = {
    model: HIA_SOURCE_MODEL,
    modelVersion: HIA_SOURCE_MODEL_VERSION,
    mode: toSourceMode(value.mode)
  };
  const definedIn = mapSourceDefinedIn(value.definedIn);
  const primaryBlock = mapSourcePrimaryBlock(value.primaryBlock);
  const references = mapSourceReferences(value.references);
  const fragments = mapSourceFragments(value.fragments);
  const diagnostics = mapDiagnostics(value.diagnostics, "source.diagnostics");

  if (definedIn) {
    source.definedIn = definedIn;
  }

  if (value.primaryBlock === null) {
    source.primaryBlock = null;
  } else if (primaryBlock) {
    source.primaryBlock = primaryBlock;
  }

  if (references.length > 0) {
    source.references = references;
  }

  if (fragments.length > 0) {
    source.fragments = fragments;
  }

  if (diagnostics.length > 0) {
    source.diagnostics = diagnostics;
  }

  return source;
}

function mapSourceDefinedIn(value: unknown): HiaSourceDefinedIn | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const relativePath = toRelativePath(value.relativePath);
  const position = mapPosition(value.position);

  if (!relativePath || !position) {
    return undefined;
  }

  const definedIn: HiaSourceDefinedIn = {
    kind: "defined-in",
    relativePath,
    position
  };
  const language = stringValue(value.language);
  const range = mapRange(value.range);
  const link = mapSourceLink(value.link);

  if (language) {
    definedIn.language = language;
  }

  if (range) {
    definedIn.range = range;
  }

  if (link) {
    definedIn.link = link;
  }

  return definedIn;
}

function mapSourcePrimaryBlock(value: unknown): HiaSourcePrimaryBlock | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const content = stringValue(value.content);
  const primaryBlock: HiaSourcePrimaryBlock = {
    kind: "primary-block",
    content,
    rangeSource: toRangeSource(value.rangeSource),
    confidence: toConfidence(value.confidence)
  };
  const id = stringValue(value.id);
  const relativePath = toRelativePath(value.relativePath);
  const language = stringValue(value.language);
  const range = mapRange(value.range);
  const link = mapSourceLink(value.link);
  const preview = mapSourcePreview(value.preview);
  const diagnostics = mapDiagnostics(value.diagnostics, "source.primaryBlock.diagnostics");

  if (id) {
    primaryBlock.id = id;
  }

  if (relativePath) {
    primaryBlock.relativePath = relativePath;
  }

  if (language) {
    primaryBlock.language = language;
  }

  if (range) {
    primaryBlock.range = range;
  }

  if (link) {
    primaryBlock.link = link;
  }

  if (preview) {
    primaryBlock.preview = preview;
  }

  if (diagnostics.length > 0) {
    primaryBlock.diagnostics = diagnostics;
  }

  return primaryBlock;
}

function mapSourceReferences(value: unknown): HiaSourceReference[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const references = value
    .map((item): HiaSourceReference | null => {
      if (!isRecord(item)) {
        return null;
      }

      const targetId = stringValue(item.targetId);

      if (!targetId) {
        return null;
      }

      const reference: HiaSourceReference = {
        kind: "source-reference",
        referenceKind: stringValue(item.referenceKind) || "coderef",
        targetId,
        resolved: item.resolved === true
      };
      const sourceNodeId = stringValue(item.sourceNodeId);
      const fieldPath = stringValue(item.fieldPath);
      const fragment = mapSourceFragment(item.fragment);
      const diagnostics = mapDiagnostics(item.diagnostics, "source.references.diagnostics");

      if (sourceNodeId) {
        reference.sourceNodeId = sourceNodeId;
      }

      if (fieldPath) {
        reference.fieldPath = fieldPath;
      }

      if (fragment) {
        reference.fragment = fragment;
      }

      if (diagnostics.length > 0) {
        reference.diagnostics = diagnostics;
      }

      return reference;
    })
    .filter((item): item is HiaSourceReference => Boolean(item));

  return dedupeSourceReferences(references);
}

function mapSourceFragments(value: unknown): HiaSourceFragment[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const fragments = value
    .map((item) => mapSourceFragment(item))
    .filter((item): item is HiaSourceFragment => Boolean(item));

  return dedupeSourceFragments(fragments);
}

function mapSourceFragment(value: unknown): HiaSourceFragment | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const id = stringValue(value.id);
  const relativePath = toRelativePath(value.relativePath);
  const range = mapRange(value.range);

  if (!id || !relativePath || !range) {
    return undefined;
  }

  const fragment: HiaSourceFragment = {
    kind: "source-fragment",
    id,
    relativePath,
    range,
    content: stringValue(value.content),
    rangeSource: toRangeSource(value.rangeSource) === "unresolved" ? "manual" : toRangeSource(value.rangeSource),
    confidence: toConfidence(value.confidence) === "none" ? "high" : toConfidence(value.confidence)
  };
  const language = stringValue(value.language);
  const origin = isRecord(value.origin) ? sanitizeMetadata(value.origin) : undefined;
  const link = mapSourceLink(value.link);
  const preview = mapSourcePreview(value.preview);
  const diagnostics = mapDiagnostics(value.diagnostics, "source.fragments.diagnostics");

  if (language) {
    fragment.language = language;
  }

  if (isRecord(origin)) {
    fragment.origin = origin;
  }

  if (link) {
    fragment.link = link;
  }

  if (preview) {
    fragment.preview = preview;
  }

  if (diagnostics.length > 0) {
    fragment.diagnostics = diagnostics;
  }

  return fragment;
}

function mapSourceLink(value: unknown): HiaSourceLink | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const link: HiaSourceLink = {
    enabled: value.enabled !== false
  };
  const fileUrl = stringValue(value.fileUrl);
  const lineUrl = stringValue(value.lineUrl);
  const openMode = stringValue(value.openMode);

  if (fileUrl) {
    link.fileUrl = fileUrl;
  }

  if (lineUrl) {
    link.lineUrl = lineUrl;
  }

  const normalizedOpenMode = toSourceOpenMode(openMode);

  if (normalizedOpenMode) {
    link.openMode = normalizedOpenMode;
  }

  return link;
}

function mapSourcePreview(value: unknown): HiaSourcePreview | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const preview: HiaSourcePreview = {
    enabled: value.enabled !== false
  };
  const content = stringValue(value.content);
  const language = stringValue(value.language);
  const range = mapRange(value.range);

  if (typeof value.defaultExpanded === "boolean") {
    preview.defaultExpanded = value.defaultExpanded;
  }

  if (content) {
    preview.content = content;
  }

  if (language) {
    preview.language = language;
  }

  if (range) {
    preview.range = range;
  }

  return preview;
}

function mapPosition(value: unknown): HiaSourcePosition | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const line = numberValue(value.line);

  if (!Number.isInteger(line) || line < 1) {
    return undefined;
  }

  const position: HiaSourcePosition = { line };
  const column = numberValue(value.column);

  if (Number.isInteger(column) && column > 0) {
    position.column = column;
  }

  return position;
}

function mapRange(value: unknown): HiaSourceRange | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const start = mapPosition(value.start);
  const end = mapPosition(value.end);

  if (!start || !end) {
    return undefined;
  }

  return {
    start,
    end
  };
}

function mapLangBlocks(value: unknown, fallbackFieldPath: string): HiaLangBlock[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item): HiaLangBlock | null => {
      if (!isRecord(item)) {
        return null;
      }

      const locale = stringValue(item.locale);
      const text = stringValue(item.text);

      if (!locale || !text) {
        return null;
      }

      const block: HiaLangBlock = {
        kind: "lang-block",
        locale,
        fieldPath: stringValue(item.fieldPath) || fallbackFieldPath,
        text
      };
      const source = stringValue(item.source);
      const rangeInComment = mapTextRange(item.rangeInComment);

      if (source) {
        block.source = source;
      }

      if (rangeInComment) {
        block.rangeInComment = rangeInComment;
      }

      return block;
    })
    .filter((item): item is HiaLangBlock => Boolean(item));
}

function mapLangInlineSegments(value: unknown, fallbackFieldPath: string): HiaLangInlineSegment[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item, index): HiaLangInlineSegment | null => {
      if (!isRecord(item)) {
        return null;
      }

      const localized = mapLocalizedText(item.localized);

      if (Object.keys(localized).length === 0) {
        return null;
      }

      const segment: HiaLangInlineSegment = {
        kind: "lang-inline",
        id: stringValue(item.id) || `${fallbackFieldPath}.${index}`,
        fieldPath: stringValue(item.fieldPath) || fallbackFieldPath,
        raw: stringValue(item.raw),
        localized
      };
      const key = stringValue(item.key);
      const path = stringValue(item.path);
      const rangeInField = mapTextRange(item.rangeInField);

      if (key) {
        segment.key = key;
      }

      if (path) {
        segment.path = path;
      }

      if (rangeInField) {
        segment.rangeInField = rangeInField;
      }

      return segment;
    })
    .filter((item): item is HiaLangInlineSegment => Boolean(item));
}

function mapTextRange(value: unknown): { start: number; end: number } | undefined {
  if (!isRecord(value)) {
    return undefined;
  }

  const start = numberValue(value.start);
  const end = numberValue(value.end);

  if (!Number.isInteger(start) || !Number.isInteger(end)) {
    return undefined;
  }

  return {
    start,
    end
  };
}

function mapTextResolutions(value: unknown): Record<string, HiaTextResolution> {
  if (!isRecord(value)) {
    return {};
  }

  const resolutions: Record<string, HiaTextResolution> = {};

  for (const [locale, rawResolution] of Object.entries(value)) {
    if (!isRecord(rawResolution)) {
      continue;
    }

    const requestedLocale = stringValue(rawResolution.requestedLocale) || locale;
    const resolvedLocale = stringValue(rawResolution.resolvedLocale) || requestedLocale;
    resolutions[locale] = {
      requestedLocale,
      resolvedLocale,
      fallbackChain: collectStringArray(rawResolution.fallbackChain, [requestedLocale]),
      usedFallback: rawResolution.usedFallback === true,
      missing: rawResolution.missing === true
    };
  }

  return resolutions;
}

function mapI18nResources(value: unknown): HiaI18nResource[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item): HiaI18nResource | null => {
      if (!isRecord(item)) {
        return null;
      }

      const path = toRelativePath(item.path) || stringValue(item.name) || "";

      if (!path) {
        return null;
      }

      const resource: HiaI18nResource = { path };
      const kind = stringValue(item.kind);
      const locale = stringValue(item.locale);
      const format = stringValue(item.format);
      const fields = collectStringArray(item.fields);

      if (kind) {
        resource.kind = kind;
      }

      if (locale) {
        resource.locale = locale;
      }

      if (format) {
        resource.format = format;
      }

      if (fields.length > 0) {
        resource.fields = fields;
      }

      return resource;
    })
    .filter((item): item is HiaI18nResource => Boolean(item));
}

function mapLocalizedText(value: unknown): HiaLocalizedText {
  if (!isRecord(value)) {
    return {};
  }

  const localizedText: HiaLocalizedText = {};

  for (const [locale, text] of Object.entries(value)) {
    if (typeof text === "string") {
      localizedText[locale] = text;
    }
  }

  return localizedText;
}

function mapDiagnostics(value: unknown, targetPathPrefix: string): HiaDiagnostic[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item, index): HiaDiagnostic | null => {
      if (!isRecord(item)) {
        return null;
      }

      const diagnostic = createDiagnostic(
        stringValue(item.code) || "HIA_JSDOC_ADAPTER_DIAGNOSTIC",
        stringValue(item.message) || "JSDoc adapter diagnostic.",
        toSeverity(item.severity),
        stringValue(item.targetPath) || `${targetPathPrefix}.${index}`,
        sanitizeDiagnosticData(item.data)
      );
      const path = stringValue(item.path);

      if (path) {
        diagnostic.path = path;
      }

      return diagnostic;
    })
    .filter((item): item is HiaDiagnostic => Boolean(item));
}

function chooseSummary(node: Record<string, unknown>, i18n: HiaI18nModel | undefined, defaultLocale: string): string {
  const field = i18n?.fields.description;
  return field?.localizedText[defaultLocale] ?? field?.defaultText ?? stringValue(node.summary) ?? stringValue(node.title) ?? "";
}

function collectLocales(nodes: unknown[], optionsLocales: string[] | undefined, defaultLocale: string): string[] {
  const locales: string[] = [];

  for (const locale of optionsLocales ?? []) {
    pushUnique(locales, locale);
  }

  pushUnique(locales, defaultLocale);

  for (const node of nodes) {
    if (!isRecord(node) || !isRecord(node.i18n)) {
      continue;
    }

    for (const locale of collectStringArray(node.i18n.locales)) {
      pushUnique(locales, locale);
    }
  }

  return locales;
}

function findFirstString(nodes: unknown[], path: string): string | undefined {
  const segments = path.split(".");

  for (const node of nodes) {
    let current: unknown = node;

    for (const segment of segments) {
      if (!isRecord(current)) {
        current = undefined;
        break;
      }

      current = current[segment];
    }

    const value = stringValue(current);
    if (value) {
      return value;
    }
  }

  return undefined;
}

function findFirstFallbackLocale(nodes: unknown[]): HiaFallbackLocale | undefined {
  for (const node of nodes) {
    if (!isRecord(node) || !isRecord(node.i18n)) {
      continue;
    }

    const fallbackLocale = normalizeFallbackLocale(node.i18n.fallbackLocale);
    if (fallbackLocale) {
      return fallbackLocale;
    }
  }

  return undefined;
}

function normalizeFallbackLocale(value: unknown): HiaFallbackLocale | undefined {
  if (typeof value === "string" && value.length > 0) {
    return value;
  }

  const values = collectStringArray(value);

  return values.length > 0 ? values : undefined;
}

function collectStringArray(value: unknown, fallback: string[] = []): string[] {
  if (!Array.isArray(value)) {
    return fallback;
  }

  const result: string[] = [];

  for (const item of value) {
    const text = stringValue(item);
    if (text) {
      pushUnique(result, text);
    }
  }

  return result.length > 0 ? result : fallback;
}

function pushUnique(items: string[], value: string): void {
  if (value && !items.includes(value)) {
    items.push(value);
  }
}

function toSourceMode(value: unknown): HiaSourceMode {
  return value === "none" || value === "link" || value === "include" || value === "all"
    ? value
    : "all";
}

function toRangeSource(value: unknown): HiaSourceRangeSource {
  return value === "heuristic" || value === "parser" || value === "parser-js" || value === "jsdoc-meta" || value === "manual" || value === "unresolved"
    ? value
    : "unresolved";
}

function toConfidence(value: unknown): HiaSourceConfidence {
  return value === "high" || value === "medium" || value === "low" || value === "none"
    ? value
    : "none";
}

function toSeverity(value: unknown): HiaDiagnosticSeverity {
  if (value === "info" || value === "warning" || value === "error") {
    return value;
  }

  return value === "hint" ? "info" : "warning";
}

function toSourceOpenMode(value: unknown): HiaSourceLink["openMode"] | undefined {
  if (value === "new-tab" || value === "newTab" || value === "external") {
    return "new-tab";
  }

  if (value === "same-tab" || value === "sameTab" || value === "currentPage" || value === "current-page") {
    return "same-tab";
  }

  return undefined;
}

function dedupeSymbols(symbols: HiaSymbol[]): HiaSymbol[] {
  const result: HiaSymbol[] = [];
  const indexesById = new Map<string, number>();

  for (const symbol of symbols) {
    const existingIndex = indexesById.get(symbol.id);

    if (existingIndex === undefined) {
      indexesById.set(symbol.id, result.length);
      result.push(symbol);
      continue;
    }

    const existing = result[existingIndex];

    if (!existing || scoreSymbol(symbol) > scoreSymbol(existing)) {
      result[existingIndex] = symbol;
    }
  }

  return result;
}

function scoreSymbol(symbol: HiaSymbol): number {
  let score = 0;

  if (symbol.summary) {
    score += 100;
  }

  score += countI18nFieldContent(symbol.i18n?.fields) * 20;
  score += countJSDocArrayMetadata(symbol, "params") * 10;
  score += countJSDocArrayMetadata(symbol, "returns") * 10;
  score += countJSDocArrayMetadata(symbol, "properties") * 8;
  score += countJSDocArrayMetadata(symbol, "examples") * 8;

  if (symbol.source?.primaryBlock) {
    score += 4;
  }

  if (symbol.source?.definedIn) {
    score += 2;
  }

  score += symbol.diagnostics?.length ?? 0;

  return score;
}

function hasUserFacingSymbolContent(symbol: HiaSymbol): boolean {
  if (!symbol.name) {
    return false;
  }

  return Boolean(symbol.summary)
    || countI18nFieldContent(symbol.i18n?.fields) > 0
    || countJSDocArrayMetadata(symbol, "params") > 0
    || countJSDocArrayMetadata(symbol, "returns") > 0
    || countJSDocArrayMetadata(symbol, "properties") > 0
    || countJSDocArrayMetadata(symbol, "examples") > 0
    || Boolean(symbol.diagnostics?.length);
}

function countI18nFieldContent(fields: HiaI18nModel["fields"] | undefined): number {
  if (!fields || !isRecord(fields)) {
    return 0;
  }

  let count = 0;

  for (const field of Object.values(fields)) {
    if (!isRecord(field)) {
      continue;
    }

    const localizedText = isRecord(field.localizedText) ? field.localizedText : {};

    if (stringValue(field.defaultText)
      || Object.values(localizedText).some((text) => stringValue(text))
      || (Array.isArray(field.blocks) && field.blocks.length > 0)
      || (Array.isArray(field.segments) && field.segments.length > 0)) {
      count += 1;
    }
  }

  return count;
}

function countJSDocArrayMetadata(symbol: HiaSymbol, field: string): number {
  if (!isRecord(symbol.metadata) || !isRecord(symbol.metadata.jsdoc)) {
    return 0;
  }

  const value = symbol.metadata.jsdoc[field];

  return Array.isArray(value) ? value.length : 0;
}

function dedupeSourceReferences(references: HiaSourceReference[]): HiaSourceReference[] {
  const result: HiaSourceReference[] = [];
  const seen = new Set<string>();

  for (const reference of references) {
    const key = [
      reference.referenceKind,
      reference.targetId,
      reference.sourceNodeId || "",
      sourceFragmentKey(reference.fragment)
    ].join("\n");

    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    result.push(reference);
  }

  return result;
}

function dedupeSourceFragments(fragments: HiaSourceFragment[]): HiaSourceFragment[] {
  const result: HiaSourceFragment[] = [];
  const seen = new Set<string>();

  for (const fragment of fragments) {
    const key = sourceFragmentKey(fragment);

    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    result.push(fragment);
  }

  return result;
}

function sourceFragmentKey(fragment: HiaSourceFragment | undefined): string {
  if (!fragment) {
    return "";
  }

  return [
    fragment.id,
    fragment.relativePath,
    fragment.range?.start.line ?? "",
    fragment.range?.start.column ?? "",
    fragment.range?.end.line ?? "",
    fragment.range?.end.column ?? "",
    fragment.content
  ].join("\n");
}

function toRelativePath(value: unknown): string {
  const text = stringValue(value).replace(/\\/g, "/");

  return isUnsafePathLike(text) ? "" : text;
}

function sanitizeMetadata(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => sanitizeMetadata(item)).filter((item) => item !== undefined);
  }

  if (isRecord(value)) {
    const record: Record<string, unknown> = {};

    for (const [key, item] of Object.entries(value)) {
      if (/filePath$/i.test(key)) {
        continue;
      }

      const sanitized = sanitizeMetadata(item);
      if (sanitized !== undefined) {
        record[key] = sanitized;
      }
    }

    return record;
  }

  if (typeof value === "string" && isUnsafePathLike(value)) {
    return undefined;
  }

  return value;
}

function sanitizeDiagnosticData(value: unknown): HiaDiagnosticData | undefined {
  const sanitized = sanitizeMetadata(value);

  return isRecord(sanitized) ? sanitized : undefined;
}

function filterDocletNodeMap(value: unknown, symbolIds: Set<string>): unknown {
  if (!Array.isArray(value)) {
    return [];
  }

  const result: unknown[] = [];
  const seen = new Set<string>();

  for (const item of value) {
    if (!isRecord(item)) {
      continue;
    }

    const nodeId = stringValue(item.nodeId);

    if (!symbolIds.has(nodeId)) {
      continue;
    }

    const key = `${stringValue(item.docletId)}\n${nodeId}`;

    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    result.push(item);
  }

  return result;
}

function isUnsafePathLike(value: string): boolean {
  const normalized = value.replace(/\\/g, "/");

  return /^[A-Za-z]:[\\/]/.test(value)
    || normalized.startsWith("/")
    || normalized.startsWith("//")
    || normalized === ".."
    || normalized.startsWith("../")
    || normalized.includes("/../")
    || normalized.endsWith("/..");
}

function createDiagnostic(
  code: string,
  message: string,
  severity: HiaDiagnosticSeverity,
  targetPath?: string,
  data?: HiaDiagnosticData
): HiaDiagnostic {
  const options: {
    data?: HiaDiagnosticData;
    targetPath?: string;
  } = {};

  if (targetPath) {
    options.targetPath = targetPath;
  }

  if (data) {
    options.data = data;
  }

  return createHiaDiagnostic(code, message, severity, options);
}

function stringValue(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function numberValue(value: unknown): number {
  return typeof value === "number" ? value : Number.NaN;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
